pipeline {
    agent any
    tools {
        jdk 'JDK 17'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/andrescamilo35/Producto.git', branch: 'master'
            }
        }
        stage('Preparar') {
            steps {
                 sh 'chmod +x ./gradlew'
            }
        }
        stage('Build') {
            steps {
                sh './gradlew build'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Package') {
            steps {
                sh './gradlew assemble'
            }
        }
    }
}
